# Form implementation generated from reading ui file 'ui_droitereg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1499, 955)
        MainWindow.setStyleSheet("/* Styles généraux */\n"
"QWidget {\n"
"    background-color: #FAFAFA;\n"
"    color: #333333;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* MainWindow */\n"
"QMainWindow {\n"
"    background-color: #FAFAFA;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* Boutons */\n"
"QPushButton {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 3px;\n"
"    padding: 4px 8px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"    color: #333333;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C96868;\n"
"    border-color: #B55555;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7EACB5;\n"
"    border-color: #5E9CA5;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F8F8F8;\n"
"    border-color: #E0E0E0;\n"
"    color: #999999;\n"
"}\n"
"\n"
"/* TableWidget */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    color: #333333;\n"
"    gridline-color: #E5E5E5;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"    border: 1px solid #E0E0E0;\n"
"    selection-background-color: #7EACB5;\n"
"    selection-color: #FFFFFF;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px;\n"
"    border-bottom: 1px solid #F0F0F0;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #C96868;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #7EACB5;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Headers */\n"
"QHeaderView::section {\n"
"    background-color: #F0F0F0;\n"
"    color: #333333;\n"
"    padding: 4px;\n"
"    border: 1px solid #E0E0E0;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-bottom: 1px solid #D0D0D0;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-right: 1px solid #D0D0D0;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #C96868;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QHeaderView::section:pressed {\n"
"    background-color: #7EACB5;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: #333333;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* TextEdit */\n"
"QTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #333333;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 2px;\n"
"    padding: 4px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"    selection-background-color: #E0E0E0;\n"
"    selection-color: #333333;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #C0C0C0;\n"
"}\n"
"\n"
"/* ScrollBars */\n"
"QScrollBar:vertical {\n"
"    background-color: #F5F5F5;\n"
"    width: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"    border: 1px solid #D0D0D0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #D0D0D0;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background-color: transparent;\n"
"    height: 1px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #F5F5F5;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #E0E0E0;\n"
"    border-radius: 2px;\n"
"    min-width: 20px;\n"
"    border: 1px solid #D0D0D0;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #D0D0D0;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    background-color: transparent;\n"
"    width: 1px;\n"
"}\n"
"\n"
"/* ToolTips */\n"
"QToolTip {\n"
"    background-color: #FFFFFF;\n"
"    color: #333333;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 2px;\n"
"    padding: 4px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"/* Widget natif pour le graphique */\n"
"QWidget#graph_layout {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* Label signature avec style spécial */\n"
"QLabel#label_signature {\n"
"    color: #666666;\n"
"    font-weight: bold;\n"
"    font-size: 5px;\n"
"    background-color: transparent;\n"
"    padding: 2px;\n"
"}\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_signature = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_signature.setFont(font)
        self.label_signature.setObjectName("label_signature")
        self.gridLayout.addWidget(self.label_signature, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_remplissage = QtWidgets.QPushButton(parent=self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/file_down"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_remplissage.setIcon(icon)
        self.pushButton_remplissage.setObjectName("pushButton_remplissage")
        self.verticalLayout.addWidget(self.pushButton_remplissage)
        self.pushButton_droitereg = QtWidgets.QPushButton(parent=self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/chart_line"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_droitereg.setIcon(icon1)
        self.pushButton_droitereg.setObjectName("pushButton_droitereg")
        self.verticalLayout.addWidget(self.pushButton_droitereg)
        self.pushButton_print = QtWidgets.QPushButton(parent=self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/printer"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_print.setIcon(icon2)
        self.pushButton_print.setObjectName("pushButton_print")
        self.verticalLayout.addWidget(self.pushButton_print)
        self.pushButton_zero = QtWidgets.QPushButton(parent=self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/eraser"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_zero.setIcon(icon3)
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.verticalLayout.addWidget(self.pushButton_zero)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textEdit_commentaires = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_commentaires.setObjectName("textEdit_commentaires")
        self.verticalLayout_2.addWidget(self.textEdit_commentaires)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.graph_layout = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_layout.sizePolicy().hasHeightForWidth())
        self.graph_layout.setSizePolicy(sizePolicy)
        self.graph_layout.setMinimumSize(QtCore.QSize(851, 491))
        self.graph_layout.setMaximumSize(QtCore.QSize(851, 491))
        self.graph_layout.setObjectName("graph_layout")
        self.verticalLayout_3.addWidget(self.graph_layout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_data = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_data.setMinimumSize(QtCore.QSize(601, 861))
        self.tableWidget_data.setMaximumSize(QtCore.QSize(601, 861))
        self.tableWidget_data.setObjectName("tableWidget_data")
        self.tableWidget_data.setColumnCount(0)
        self.tableWidget_data.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_data)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_signature.setText(_translate("MainWindow", "By : Tristan Gayrard 👍😎"))
        self.pushButton_remplissage.setText(_translate("MainWindow", "Exemple remplissage"))
        self.pushButton_droitereg.setText(_translate("MainWindow", "Régression Linéaire"))
        self.pushButton_print.setText(_translate("MainWindow", "Imprimer"))
        self.pushButton_zero.setText(_translate("MainWindow", "Zero"))
        self.label.setText(_translate("MainWindow", "Commentaires :"))
